spring: 
  application: 
     name: vendor
  datasource:     url: jdbc:mysql://localhost:3306/supplierDB
    username: admin
    password: admin
  jpa:
    hibernate: 
      ddl-auto: none
 
server: 
  port: 8089
  servlet: 
    contextPath: /default
name: default-yml
environment: default
enabled: true
contextpath: /default
servers: 
   - www.default.com
   - www.default1.com
logging: 
      file: 
        name: logs/default_logs.log
      pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
        file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
      level:
        org.springframework.web: ERROR
        org.fintexel.supplier.*: INFO
        org.hibernate: ERROR
   
---
spring: 
  profiles: dev
  application: 
     name: vendor
  datasource: 
    url: jdbc:mysql://decisionbox.cqmq67eyfk9g.ap-south-1.rds.amazonaws.com:3306/flowable
    username: datadox
    password: ruucP2kyzpSfVLc48ati
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    hibernate: 
      ddl-auto: none
      use-new-id-generator-mappings: false
server: 
  port: 8088
  servlet: 
    contextPath: /dev
name: dev-yml
environment: dev
enabled: true
contextpath: /dev
servers: 
   - www.dev.com
   - www.dev1.com
logging: 
      file: 
        name: logs/dev_logs.log
      pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
        file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
      level:
        org.springframework.web: ERROR
        org.fintexel.supplier.*: INFO
        org.hibernate: ERROR
        
connection: 
  pool: 
    initialPoolSize: 5
    minPoolSize: 10
    maxPoolSize: 20
    maxIdleTime: 3000
    
spring.servlet.multipart:
  enabled: true
  max-file-size: 100MB
#file.upload-path: C:\\Users\\shant\\Desktop\\uploadfile\\
file.upload-path: /home/ubuntu/supplierApp/fileuploaded/
---
spring: 
  profiles: prod
  application: 
     name: vendor
  datasource: 
    url: jdbc:mysql://localhost:3306/supplierDB
    username: admin
    password: admin
  jpa:
    hibernate: 
      ddl-auto: none
      use-new-id-generator-mappings: false
server: 
  port: 8087
  servlet: 
    contextPath: /prod
name: prod-yml
environment: prod
enabled: true
contextpath: /prod
servers: 
   - prod
   - prod.com
logging: 
      file: 
        name: logs/prod_logs.log
      pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
        file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
      level:
        org.springframework.web: ERROR
        org.fintexel.supplier.*: INFO
        org.hibernate: ERROR
        
    
#spring: 
#  profiles: dev2
#  application: 
#     name: vendor
#  datasource: 
#    url: jdbc:mysql://decisionbox.cqmq67eyfk9g.ap-south-1.rds.amazonaws.com:3306/flowable
#    username: datadox
#    password: ruucP2kyzpSfVLc48ati
#    driverClassName: com.mysql.jdbc.Driver
#  jpa:
#    hibernate: 
#      ddl-auto: none
#      use-new-id-generator-mappings: false
#server: 
#  port: 8088
#  servlet: 
#    contextPath: /dev
#name: dev-yml
#environment: dev
#enabled: true
#contextpath: /dev
#servers: 
#   - www.dev.com
#   - www.dev1.com
#logging: 
#      file: 
#        name: logs/dev_logs.log
#      pattern:
#        console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
#        file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
#      level:
#        org.springframework.web: ERROR
#        org.fintexel.supplier.*: INFO
#        org.hibernate: ERROR